import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: '#0f0f0f',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
    fontFamily: 'system-ui, sans-serif',
  },
  centered: {
    minHeight: '100vh',
    background: '#0f0f0f',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: { width: '100%', maxWidth: 520 },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  roundBadge: {
    background: '#1a1a1a',
    border: '1px solid #2a2a2a',
    padding: '0.4rem 0.875rem',
    borderRadius: '999px',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#888',
  },
  timer: { fontSize: '1.5rem', fontWeight: 900 },
  memeImage: {
    width: '100%',
    borderRadius: '1rem',
    marginBottom: '1.5rem',
    border: '1px solid #2a2a2a',
  },
  submittedCount: {
    color: '#555',
    fontSize: '0.875rem',
    textAlign: 'center',
    marginBottom: '1rem',
  },
  captionBox: { display: 'flex', flexDirection: 'column', gap: '0.75rem' },
  textarea: {
    width: '100%',
    padding: '1rem',
    borderRadius: '0.75rem',
    border: '1px solid #333',
    background: '#1a1a1a',
    color: '#fff',
    fontSize: '1rem',
    resize: 'none',
    outline: 'none',
    fontFamily: 'system-ui, sans-serif',
    boxSizing: 'border-box',
  },
  waitingBox: {
    background: '#1a1a1a',
    border: '1px solid #2a2a2a',
    borderRadius: '0.75rem',
    padding: '1.5rem',
    textAlign: 'center',
  },
  primaryBtn: {
    width: '100%',
    padding: '0.875rem',
    borderRadius: '0.75rem',
    background: '#ff6b00',
    color: '#fff',
    fontWeight: 700,
    fontSize: '1rem',
    border: 'none',
    cursor: 'pointer',
  },
  captionOption: {
    width: '100%',
    padding: '1rem',
    borderRadius: '0.75rem',
    background: '#1a1a1a',
    color: '#fff',
    fontWeight: 600,
    fontSize: '1rem',
    textAlign: 'left',
  },
  winnerCard: {
    background: '#1a1a1a',
    border: '1px solid #ff6b0033',
    borderRadius: '1rem',
    padding: '1.5rem',
    textAlign: 'center',
    marginTop: '1rem',
  },
  scoreRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.75rem 1rem',
    borderRadius: '0.75rem',
    marginBottom: '0.5rem',
    background: '#111',
  },
};
